name: CI

on:
  push:
    branches: [main]
    tags: ['v*.*.*']          # release tag'lerinde de çalışsın
    paths-ignore:             # gereksiz değişikliklerde tetiklenmesin
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
  workflow_dispatch:          # elle tetikleme

# Aynı branch'te yeni run gelirse eskisini iptal et
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]          # ana desteklenen sürüm
        include:
          - node-version: 22.x        # paralel deneme
            experimental: true

    name: build (${{ matrix.node-version }})
    continue-on-error: ${{ matrix.experimental == true }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }} + npm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      # Next.js / Turbopack cache (build'i hızlandırır)
      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Test
        run: npm test --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build
