name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Aynı branşta yeni bir run gelirse öncekini iptal et
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 20.x
            experimental: false
          - node-version: 22.x
            experimental: true

    # 22.x job'u deneysel: başarısız olursa workflow kırılmasın
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }} + cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      # engines (node:20.x) kuralını 22.x job'unda gevşet
      - name: Install deps (stable)
        if: ${{ !matrix.experimental }}
        run: npm ci

      - name: Install deps (experimental - ignore engines)
        if: ${{ matrix.experimental }}
        run: npm ci --engine-strict=false

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
