name: CI
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Debug (paths & versions)
        run: |
          pwd
          ls -la
          node -v
          npm -v
          test -f package.json || (echo "❌ package.json yok!" && exit 1)
          head -n 40 package.json

      # Peer çakışmaları + postinstall scriptleri CI'yi düşürmesin
      - name: Install
        run: npm install --no-audit --no-fund --legacy-peer-deps --ignore-scripts
        env:
          CI: true
          HUSKY: 0

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build





