name: CI

on:
  push:
    branches: [main]
    # (İsteğe bağlı) tag push'larında da çalışsın istiyorsan aç:
    # tags: ['v*.*.*']
    paths-ignore:
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.vscode/**'
      - 'docs/**'
  workflow_dispatch:

# Aynı branch'te yeni run gelirse eskisini iptal et
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Minimum izin
permissions:
  contents: read

jobs:
  build:
    # ⚠️ Job adı BİLEREK "build". Branch protection'taki required check ile birebir uyumlu.
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Type check (if tsconfig exists)
        if: hashFiles('**/tsconfig.json') != ''
        run: npx tsc --noEmit --pretty false

      - name: Run tests (if present)
        run: npm test --if-present -- --ci

      - name: Build
        run: npm run build
